### PR TITLE
Created check prime number function

### LINKED ISSUE #42: [Beginner/Experienced] Implement is_prime function to existing is_prime.py in BC
• Add new feature using any algorithm
• Add docstring to explain the function using Google Style

Experienced:
• Convert and rename the file and function to get all primes up to x
• Implement an optimal algorithm to achieve this

### PR DESCRIPTION
**Pull request by hufahamdika**

### CODE REVIEW

**Comment by abyoso-hapsoro** [comment]
1 is not a prime number :)

**Comment by hufahamdika** [comment]
ahahahaha my bad, will fix it in a minute

**Comment by hufahamdika** [comment]
just fixed the problem :)

**Comment by abyoso-hapsoro** [comment]
No problem, haha. Hope you enjoyed practicing to create a pull request! Feel free to experiment more if desired.

P.S. This can be made more efficient actually, you only need to check up to `math.floor(num**0.5)` and make the step 2 at a time (instead of the default 1 at a time) starting the check from 3

**Pull request merged**
